language: go

go:
  - tip
  - 1.16.x
  - 1.15.x
  - 1.14.x
  - 1.13.x
  - 1.12.x
  
env:
  - GO111MODULE=on

before_install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.38.0

jobs:
  include:
    - stage: lint
      script: make lint
    - stage: test
      script: make testcov COVER_PROFILE_FILENAME=coverage.txt

after_success:
  - bash <(curl -s https://codecov.io/bash)
